# -*- coding: utf-8 -*-
"""Aiml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t261RZim5AW0UWoiNq2LDKl8cDGBuq91
"""

 from google.colab import files
ss = files.upload()

import pandas as pd
import numpy as np
pd.read_csv("supermarket_sales.csv")

df = pd.read_csv("supermarket_sales.csv")
df.info()

df.head()

df.tail()

df.Total.describe()

df.describe(include = "all")

df.describe(exclude = ['object','int'])

df['Total'].describe(percentiles=[.20, .40, .60, .80])

df.City.value_counts(ascending=True, normalize=True)

df.max()

df.nunique()

df.City.nunique()

df['Quantity'].sum()

df.sum(numeric_only=True)

df.count()

df.City.count()

df.min()

df.Rating.mean()

df[['Total','cogs','Tax 5%']].agg(['count','min','max','mean','median','sum'])